[package]
name = 'aptogotchi'
version = '1.0.0'
upgrade_policy = "compatible"

[addresses]
aptogotchi_addr = '71cc7f10ea20de366f1d512369df023e607fe14261e815c289eec8dc6b3ea7fe'

[dependencies.AptosFramework]
git = 'https://github.com/aptos-labs/aptos-core.git'
rev = 'main'
subdir = 'aptos-move/framework/aptos-framework'

[dependencies.AptosTokenObjects]
git = 'https://github.com/aptos-labs/aptos-core.git'
rev = 'main'
subdir = 'aptos-move/framework/aptos-token-objects'
